services:
  fast:
    build: ./fast
    ports:
      - "8000:8000"
    environment:
      SQL_USER: admin1
      SQL_PASSWORD: 12341
      SQL_URL: "db:5432"
      SQL_DB: disaster_io
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: 12341
      POSTGRES_DB: disaster_io
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  web:
    build: ./solid
    expose:
      - "3000"
  
  nginx:
    image: nginx:1.23-alpine
    restart: always
    depends_on:
      - web
      - fast
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


volumes:
  postgres_data:
